### PR TITLE
DPD Carrier codes not correct !

### PR DESCRIPTION
**Pull request by RUDIWER**

### CODE REVIEW

**Comment by RUDIWER** [comment]
Added possibility to ship with shippinglabel codes -> is needed to print shippinglabels !

**Comment by xewl** [comment]
Can a milestone be made for this change?
v0.2.6 stable which is pulled in by composer/packagist still uses the old codes.

**Comment by meertensm** [comment]
I've just created 0.2.7. Hopefully this works

**Comment by xewl** [comment]
Works as intended, thanks @meertensm !!

**Pull request closed without merging**
