### PR TITLE
Plaza API v2 Bulk update offers

### PR DESCRIPTION
**Pull request by gwinn**

### CODE REVIEW

**Comment by YachYaroslav** [comment]
@meertensm, can you merge these changes? I am really in need of v2 offers...

**Comment by meertensm** [comment]
Can someone please explain to me what actually changed?
All changes should be backward-compatible. If i merge this pull request, will people run into trouble when they do a composer update?

**Comment by gwinn** [comment]
this update refer to https://developers.bol.com/offer-api-v2/create-and-update/

**Comment by YachYaroslav** [comment]
@meertensm, I made double check and I think you have not to merge this, because @gwinn only changed urls for request not the methods, which do these request. That's why for example stock update will not work. I think we need firstly make special condition for backward compatibility with 1st and 2nd versions. There still are needed more changes to merge in master.

**Pull request closed without merging**
